name: Workflow 1
on: push
jobs:
  lint-test-build-artifact:
    name: Lint Test Build Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact-files
          path: dist
  deploy:
    name: Deploy
    needs: lint-test-build-artifact
    runs-on: ubuntu-latest
    steps:
      - name: Dwonload Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact-files
      - name: Log Artifact Content
        run: ls
      - name: Deploy to host
        run: echo "deploying..."